# For more info on HTTP files go to https://aka.ms/vs/httpfile
     

# Run this script to capture a jwt for reuse in all the subsequent 
# scripts.  Visual Studio automatically deflates the token.
# @name login
POST {{HostAddress}}/api/login
Content-Type: application/json
Cache-Control: no-cache
User-Agent: Resident Eval App
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

{
  "Email": "{{username}}",
  "Password": "{{password}}"
}


###
# Demo UserProfile endpoint to test Authentication
GET {{HostAddress}}/api/userprofile
Authorization: Bearer {{login.response.body.$.access_token}}
Accept: application/json
Cache-Control: no-cache
User-Agent: Resident Eval App
Accept-Encoding: gzip, deflate, br
Connection: keep-alive


###
# CreateAccount endpoint
POST {{HostAddress}}/api/createaccount
Content-Type: application/json
Cache-Control: no-cache
User-Agent: Resident Eval App
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

{
  "email": "test@domain.com",
  "password": "Password123",
  "passwordConfirm": "Password123"
}


###
# ForgotPassword endpoint
POST {{HostAddress}}/api/forgotpassword
Content-Type: application/json
Cache-Control: no-cache
User-Agent: Resident Eval App
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

{
  "email": "test@domain.com"
}
